; Konfigurationen

[base]
url = "https://mysite.com/"
intern = ""

[session]
extensions[] = "php"
extensions[] = "json"
cookiedomain = ".mysite.com"

[manager]
stdscope = "other"
layout = "simple"

[base3xrm]
cloudurl = "https://service.mysite.de/"
restendpoint = "rest/json.php"
fileendpoint = "rest/file.php"
imageendpoint = "rest/image.php"
downloadendpoint = "rest/download.php"
previewendpoint = "rest/preview.php"
accessstdallusers = 0

[scriptlock]
; declineremoteaddr[] = "123.456."
; declineremoteaddr[] = "123.457."
; declineacceptlanguage[] = "zn"

[database]
; host = "localhost"
; user = "mydbuser"
; pass = "MyPa55w0rd!"
; name = "mydatabase"

[singleauth]
; user = "dd"
; pass = "--my-passwords-sha1-hash--"

[language]
; main = "en"
; languages[] = "en"
; languages[] = "de"
; languages[] = "es"
; languages[] = "bg"

[worker]
; active = true
; priority = 1

[microservice]
; name = "Manager"
; masterurl = "https://master.base3.de/"
; masterpass = "EV2fpJ4skSn89OysM43QuwFD0sP1sY7A"

[include]
; files[] = "../../manager.mysite.de.ini"
